/**
 * Auto-generated API implementations
 * This file is automatically generated based on your API dependencies.
 * Do not edit manually - changes will be overwritten.
 */

import { Agent } from '@greaseclaw/workflow-sdk';

/**
 * Task status type
 */
export type TaskStatus = 'waiting' | 'running' | 'succeeded' | 'failed';

/**
 * Execution result returned by all API calls
 */
export interface ExecutionResult {
  success: boolean;
  error?: string;
  task?: {
    id: string;
    status: TaskStatus;
    extract_data?: string;
    metrics_tokens: number;
    metrics_time: number;
  };
}

/**
 * WorkflowApis interface - methods generated from your API dependencies
 */
export interface WorkflowApis {
  twitter_block: (username: string) => Promise<ExecutionResult>;
  twitter_follow: (username: string) => Promise<ExecutionResult>;
  twitter_thread: (tweet_id: string, limit?: number) => Promise<ExecutionResult>;
  twitter_search: (query: string, filter?: string, limit?: number) => Promise<ExecutionResult>;
  twitter_likes: (username: string, limit?: number) => Promise<ExecutionResult>;
  twitter_like: (url: string) => Promise<ExecutionResult>;
  twitter_unblock: (username: string) => Promise<ExecutionResult>;
  twitter_bookmarks: (limit?: number) => Promise<ExecutionResult>;
  twitter_timeline: (type?: string, limit?: number) => Promise<ExecutionResult>;
  twitter_trending: (limit?: number) => Promise<ExecutionResult>;
  twitter_article: (tweet_id: string) => Promise<ExecutionResult>;
  twitter_unfollow: (username: string) => Promise<ExecutionResult>;
  twitter_bookmark: (url: string) => Promise<ExecutionResult>;
  twitter_reply: (tweet_id: string, text: string, submit?: boolean) => Promise<ExecutionResult>;
  twitter_profile: (username: string) => Promise<ExecutionResult>;
  twitter_post: (text: string, submit?: boolean) => Promise<ExecutionResult>;
  twitter_bookmark_folders: () => Promise<ExecutionResult>;
  twitter_list_remove: (list_id: string, username: string) => Promise<ExecutionResult>;
  twitter_unbookmark: (url: string) => Promise<ExecutionResult>;
  twitter_delete: (url: string) => Promise<ExecutionResult>;
  twitter_retweet: (url: string) => Promise<ExecutionResult>;
  twitter_bookmark_folder: (folder_id: string, limit?: number) => Promise<ExecutionResult>;
  twitter_list_create: (name: string, description?: string, is_private?: boolean) => Promise<ExecutionResult>;
  twitter_hide_reply: (url: string) => Promise<ExecutionResult>;
  twitter_download: (username: string, limit?: number) => Promise<ExecutionResult>;
  twitter_reply_dm: (text: string, max?: number, skip_replied?: unknown) => Promise<ExecutionResult>;
  twitter_tweets: (username: string, limit?: number) => Promise<ExecutionResult>;
  twitter_followers: (user?: string, limit?: number) => Promise<ExecutionResult>;
  twitter_accept: (query: string, max?: number) => Promise<ExecutionResult>;
  twitter_lists: (limit?: number) => Promise<ExecutionResult>;
  twitter_unlike: (url: string) => Promise<ExecutionResult>;
  twitter_quote: (url: string, text: string) => Promise<ExecutionResult>;
  twitter_notifications: (limit?: number) => Promise<ExecutionResult>;
  twitter_unretweet: (url: string) => Promise<ExecutionResult>;
  twitter_list_delete: (list_id: string) => Promise<ExecutionResult>;
  twitter_following: (user?: string, limit?: number) => Promise<ExecutionResult>;
  twitter_list_add: (list_id: string, username: string) => Promise<ExecutionResult>;
  twitter_list_tweets: (list_id: string, limit?: number) => Promise<ExecutionResult>;
  twitter_suggested: (limit?: number) => Promise<ExecutionResult>;
  twitter_list_members: (list_id: string, limit?: number) => Promise<ExecutionResult>;
  twitter_list_search: (query: string, limit?: number) => Promise<ExecutionResult>;
  weibo_group_set: (user_id: string, group_id: string, dryrun?: boolean) => Promise<ExecutionResult>;
  weibo_group_delete: (name: string, dryrun?: boolean) => Promise<ExecutionResult>;
  weibo_follow: (user_id: string) => Promise<ExecutionResult>;
  weibo_comments: (id: string, limit?: number) => Promise<ExecutionResult>;
  weibo_search: (keyword: string, limit?: number) => Promise<ExecutionResult>;
  weibo_hot: (limit?: number) => Promise<ExecutionResult>;
  weibo_group_create: (name: string, dryrun?: boolean) => Promise<ExecutionResult>;
  weibo_user: (id: string) => Promise<ExecutionResult>;
  weibo_group_list: () => Promise<ExecutionResult>;
  weibo_group_posts: (group_id: string, count?: unknown) => Promise<ExecutionResult>;
  weibo_publish: (text: string, dryrun?: boolean) => Promise<ExecutionResult>;
  weibo_me: () => Promise<ExecutionResult>;
  weibo_feed: (type?: string, limit?: number) => Promise<ExecutionResult>;
  weibo_post: (id: string) => Promise<ExecutionResult>;
}


/**
 * Creates API client using agent.call()
 */
export function createWorkflowApis(agent: Agent): WorkflowApis {
  return {
  /**
   * Block
   * Block a Twitter user
   * @endpoint /v1/custom/twitter-block
   */
  async twitter_block(username: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-block', {
      method: 'POST',
      body: { username },
    });
    return data;
  },

  /**
   * Follow
   * Follow a Twitter user
   * @endpoint /v1/custom/twitter-follow
   */
  async twitter_follow(username: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-follow', {
      method: 'POST',
      body: { username },
    });
    return data;
  },

  /**
   * Thread
   * Get a tweet thread (original + all replies)
   * @endpoint /v1/custom/twitter-thread
   */
  async twitter_thread(tweet_id: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-thread', {
      method: 'POST',
      body: { tweet_id, limit },
    });
    return data;
  },

  /**
   * Search
   * Search Twitter/X for tweets
   * @endpoint /v1/custom/twitter-search
   */
  async twitter_search(query: string, filter?: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-search', {
      method: 'POST',
      body: { query, filter, limit },
    });
    return data;
  },

  /**
   * Likes
   * Fetch liked tweets of a Twitter user
   * @endpoint /v1/custom/twitter-likes
   */
  async twitter_likes(username: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-likes', {
      method: 'POST',
      body: { username, limit },
    });
    return data;
  },

  /**
   * Like
   * Like a specific tweet
   * @endpoint /v1/custom/twitter-like
   */
  async twitter_like(url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-like', {
      method: 'POST',
      body: { url },
    });
    return data;
  },

  /**
   * Unblock
   * Unblock a Twitter user
   * @endpoint /v1/custom/twitter-unblock
   */
  async twitter_unblock(username: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-unblock', {
      method: 'POST',
      body: { username },
    });
    return data;
  },

  /**
   * Bookmarks
   * Fetch Twitter/X bookmarks
   * @endpoint /v1/custom/twitter-bookmarks
   */
  async twitter_bookmarks(limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-bookmarks', {
      method: 'POST',
      body: { limit },
    });
    return data;
  },

  /**
   * Timeline
   * Fetch Twitter timeline (for-you or following)
   * @endpoint /v1/custom/twitter-timeline
   */
  async twitter_timeline(type?: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-timeline', {
      method: 'POST',
      body: { type, limit },
    });
    return data;
  },

  /**
   * Trending
   * Twitter/X trending topics
   * @endpoint /v1/custom/twitter-trending
   */
  async twitter_trending(limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-trending', {
      method: 'POST',
      body: { limit },
    });
    return data;
  },

  /**
   * Article
   * Fetch a Twitter Article (long-form content) and export as Markdown
   * @endpoint /v1/custom/twitter-article
   */
  async twitter_article(tweet_id: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-article', {
      method: 'POST',
      body: { tweet_id },
    });
    return data;
  },

  /**
   * Unfollow
   * Unfollow a Twitter user
   * @endpoint /v1/custom/twitter-unfollow
   */
  async twitter_unfollow(username: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-unfollow', {
      method: 'POST',
      body: { username },
    });
    return data;
  },

  /**
   * Bookmark
   * Bookmark a tweet
   * @endpoint /v1/custom/twitter-bookmark
   */
  async twitter_bookmark(url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-bookmark', {
      method: 'POST',
      body: { url },
    });
    return data;
  },

  /**
   * Reply
   * Reply to a specific tweet
   * @endpoint /v1/custom/twitter-reply
   */
  async twitter_reply(tweet_id: string, text: string, submit?: boolean): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-reply', {
      method: 'POST',
      body: { tweet_id, text, submit },
    });
    return data;
  },

  /**
   * Profile
   * Fetch a Twitter user profile (bio, stats, etc.)
   * @endpoint /v1/custom/twitter-profile
   */
  async twitter_profile(username: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-profile', {
      method: 'POST',
      body: { username },
    });
    return data;
  },

  /**
   * Post
   * Post a new tweet
   * @endpoint /v1/custom/twitter-post
   */
  async twitter_post(text: string, submit?: boolean): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-post', {
      method: 'POST',
      body: { text, submit },
    });
    return data;
  },

  /**
   * BookmarkFolders
   * List your Twitter/X bookmark folders
   * @endpoint /v1/custom/twitter-bookmark-folders
   */
  async twitter_bookmark_folders(): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-bookmark-folders', {
      method: 'POST',
    });
    return data;
  },

  /**
   * ListRemove
   * Remove a user from a Twitter/X list you own
   * @endpoint /v1/custom/twitter-list-remove
   */
  async twitter_list_remove(list_id: string, username: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-list-remove', {
      method: 'POST',
      body: { list_id, username },
    });
    return data;
  },

  /**
   * Unbookmark
   * Remove a tweet from bookmarks
   * @endpoint /v1/custom/twitter-unbookmark
   */
  async twitter_unbookmark(url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-unbookmark', {
      method: 'POST',
      body: { url },
    });
    return data;
  },

  /**
   * Delete
   * Delete a tweet (must be your own)
   * @endpoint /v1/custom/twitter-delete
   */
  async twitter_delete(url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-delete', {
      method: 'POST',
      body: { url },
    });
    return data;
  },

  /**
   * Retweet
   * Retweet a tweet
   * @endpoint /v1/custom/twitter-retweet
   */
  async twitter_retweet(url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-retweet', {
      method: 'POST',
      body: { url },
    });
    return data;
  },

  /**
   * BookmarkFolder
   * Fetch tweets from a bookmark folder
   * @endpoint /v1/custom/twitter-bookmark-folder
   */
  async twitter_bookmark_folder(folder_id: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-bookmark-folder', {
      method: 'POST',
      body: { folder_id, limit },
    });
    return data;
  },

  /**
   * ListCreate
   * Create a new Twitter/X list
   * @endpoint /v1/custom/twitter-list-create
   */
  async twitter_list_create(name: string, description?: string, is_private?: boolean): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-list-create', {
      method: 'POST',
      body: { name, description, is_private },
    });
    return data;
  },

  /**
   * HideReply
   * Hide a reply to your tweet
   * @endpoint /v1/custom/twitter-hide-reply
   */
  async twitter_hide_reply(url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-hide-reply', {
      method: 'POST',
      body: { url },
    });
    return data;
  },

  /**
   * Download
   * Download media from a Twitter/X user
   * @endpoint /v1/custom/twitter-download
   */
  async twitter_download(username: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-download', {
      method: 'POST',
      body: { username, limit },
    });
    return data;
  },

  /**
   * ReplyDM
   * Send DM replies to recent conversations
   * @endpoint /v1/custom/twitter-reply-dm
   */
  async twitter_reply_dm(text: string, max?: number, skip_replied?: unknown): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-reply-dm', {
      method: 'POST',
      body: { text, max, skip_replied },
    });
    return data;
  },

  /**
   * Tweets
   * Fetch a user's recent tweets
   * @endpoint /v1/custom/twitter-tweets
   */
  async twitter_tweets(username: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-tweets', {
      method: 'POST',
      body: { username, limit },
    });
    return data;
  },

  /**
   * Followers
   * Fetch a user's followers via DOM extraction
   * @endpoint /v1/custom/twitter-followers
   */
  async twitter_followers(user?: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-followers', {
      method: 'POST',
      body: { user, limit },
    });
    return data;
  },

  /**
   * Accept
   * Accept message requests matching keywords
   * @endpoint /v1/custom/twitter-accept
   */
  async twitter_accept(query: string, max?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-accept', {
      method: 'POST',
      body: { query, max },
    });
    return data;
  },

  /**
   * Lists
   * List your Twitter/X lists
   * @endpoint /v1/custom/twitter-lists
   */
  async twitter_lists(limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-lists', {
      method: 'POST',
      body: { limit },
    });
    return data;
  },

  /**
   * Unlike
   * Unlike a tweet
   * @endpoint /v1/custom/twitter-unlike
   */
  async twitter_unlike(url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-unlike', {
      method: 'POST',
      body: { url },
    });
    return data;
  },

  /**
   * Quote
   * Quote tweet with comment
   * @endpoint /v1/custom/twitter-quote
   */
  async twitter_quote(url: string, text: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-quote', {
      method: 'POST',
      body: { url, text },
    });
    return data;
  },

  /**
   * Notifications
   * Fetch Twitter/X notifications via network intercept
   * @endpoint /v1/custom/twitter-notifications
   */
  async twitter_notifications(limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-notifications', {
      method: 'POST',
      body: { limit },
    });
    return data;
  },

  /**
   * Unretweet
   * Undo a retweet
   * @endpoint /v1/custom/twitter-unretweet
   */
  async twitter_unretweet(url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-unretweet', {
      method: 'POST',
      body: { url },
    });
    return data;
  },

  /**
   * ListDelete
   * Delete a Twitter/X list
   * @endpoint /v1/custom/twitter-list-delete
   */
  async twitter_list_delete(list_id: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-list-delete', {
      method: 'POST',
      body: { list_id },
    });
    return data;
  },

  /**
   * Following
   * Fetch accounts a user follows
   * @endpoint /v1/custom/twitter-following
   */
  async twitter_following(user?: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-following', {
      method: 'POST',
      body: { user, limit },
    });
    return data;
  },

  /**
   * ListAdd
   * Add a user to a Twitter/X list you own
   * @endpoint /v1/custom/twitter-list-add
   */
  async twitter_list_add(list_id: string, username: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-list-add', {
      method: 'POST',
      body: { list_id, username },
    });
    return data;
  },

  /**
   * ListTweets
   * Fetch tweets from a Twitter/X list
   * @endpoint /v1/custom/twitter-list-tweets
   */
  async twitter_list_tweets(list_id: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-list-tweets', {
      method: 'POST',
      body: { list_id, limit },
    });
    return data;
  },

  /**
   * Suggested
   * Get suggested users to follow from Twitter/X
   * @endpoint /v1/custom/twitter-suggested
   */
  async twitter_suggested(limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-suggested', {
      method: 'POST',
      body: { limit },
    });
    return data;
  },

  /**
   * ListMembers
   * Get members of a Twitter/X list
   * @endpoint /v1/custom/twitter-list-members
   */
  async twitter_list_members(list_id: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-list-members', {
      method: 'POST',
      body: { list_id, limit },
    });
    return data;
  },

  /**
   * ListSearch
   * Search for Twitter/X lists by name (direct GraphQL API call)
   * @endpoint /v1/custom/twitter-list-search
   */
  async twitter_list_search(query: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/twitter-list-search', {
      method: 'POST',
      body: { query, limit },
    });
    return data;
  },

  /**
   * GroupSet
   * Set a user's follow group (group_id=0 to remove from all groups)
   * @endpoint /v1/custom/weibo-group-set
   */
  async weibo_group_set(user_id: string, group_id: string, dryrun?: boolean): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-group-set', {
      method: 'POST',
      body: { user_id, group_id, dryrun },
    });
    return data;
  },

  /**
   * GroupDelete
   * Delete a Weibo follow group
   * @endpoint /v1/custom/weibo-group-delete
   */
  async weibo_group_delete(name: string, dryrun?: boolean): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-group-delete', {
      method: 'POST',
      body: { name, dryrun },
    });
    return data;
  },

  /**
   * Follow
   * Follow a Weibo user
   * @endpoint /v1/custom/weibo-follow
   */
  async weibo_follow(user_id: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-follow', {
      method: 'POST',
      body: { user_id },
    });
    return data;
  },

  /**
   * Comments
   * Get comments on a Weibo post
   * @endpoint /v1/custom/weibo-comments
   */
  async weibo_comments(id: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-comments', {
      method: 'POST',
      body: { id, limit },
    });
    return data;
  },

  /**
   * Search
   * 搜索微博
   * @endpoint /v1/custom/weibo-search
   */
  async weibo_search(keyword: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-search', {
      method: 'POST',
      body: { keyword, limit },
    });
    return data;
  },

  /**
   * Hot
   * 微博热搜
   * @endpoint /v1/custom/weibo-hot
   */
  async weibo_hot(limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-hot', {
      method: 'POST',
      body: { limit },
    });
    return data;
  },

  /**
   * GroupCreate
   * Create a new Weibo follow group
   * @endpoint /v1/custom/weibo-group-create
   */
  async weibo_group_create(name: string, dryrun?: boolean): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-group-create', {
      method: 'POST',
      body: { name, dryrun },
    });
    return data;
  },

  /**
   * User
   * Get Weibo user profile
   * @endpoint /v1/custom/weibo-user
   */
  async weibo_user(id: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-user', {
      method: 'POST',
      body: { id },
    });
    return data;
  },

  /**
   * GroupList
   * List Weibo follow groups with group IDs
   * @endpoint /v1/custom/weibo-group-list
   */
  async weibo_group_list(): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-group-list', {
      method: 'POST',
    });
    return data;
  },

  /**
   * GroupPosts
   * Get posts from a follow group
   * @endpoint /v1/custom/weibo-group-posts
   */
  async weibo_group_posts(group_id: string, count?: unknown): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-group-posts', {
      method: 'POST',
      body: { group_id, count },
    });
    return data;
  },

  /**
   * Publish
   * Publish a new Weibo post
   * @endpoint /v1/custom/weibo-publish
   */
  async weibo_publish(text: string, dryrun?: boolean): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-publish', {
      method: 'POST',
      body: { text, dryrun },
    });
    return data;
  },

  /**
   * Me
   * My Weibo profile info
   * @endpoint /v1/custom/weibo-me
   */
  async weibo_me(): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-me', {
      method: 'POST',
    });
    return data;
  },

  /**
   * Feed
   * Fetch Weibo timeline (for-you or following)
   * @endpoint /v1/custom/weibo-feed
   */
  async weibo_feed(type?: string, limit?: number): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-feed', {
      method: 'POST',
      body: { type, limit },
    });
    return data;
  },

  /**
   * Post
   * Get a single Weibo post
   * @endpoint /v1/custom/weibo-post
   */
  async weibo_post(id: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/weibo-post', {
      method: 'POST',
      body: { id },
    });
    return data;
  },
  };
}
